#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/markoviser.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/ApacheMath.jar:$APPDIR/lib/commons-math3-3.6.1-javadoc.jar:$APPDIR/lib/commons-math3-3.6.1-sources.jar:$APPDIR/lib/commons-math3-3.6.1-test-sources.jar:$APPDIR/lib/commons-math3-3.6.1-tests.jar:$APPDIR/lib/commons-math3-3.6.1-tools.jar:$APPDIR/lib/commons-math3-3.6.1.jar:$APPDIR/lib/oscP5.jar" markoviser "$@"
